import '@/styles/styles.css';
import '@/styles/colors.css';
import '@/styles/fonts.css';
import NavBar from '../components/NavBar';

export const metadata = {
  title: 'Blood Hospital',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* Contains the NavBar, comment out to remove */}
        <NavBar />
        {children}
      </body>
    </html>
  );
}
