// this file is for metadata stuff

import './css/styles.css';

export const metadata = {
  title: 'Blood Hospital',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
